services:
  web:
    build:
      context: .
      target: web
    depends_on:
      rest:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
