packages:
  - apps/*
  - packages/*

catalog:
  # Discord and Backend Services
  "@discordeno/bot": 21.0.0
  "@fastify/multipart": ^9.0.1
  "@influxdata/influxdb-client": ^1.35.0
  "amqplib": ^0.10.5
  "fastify": ^5.2.0

  # Utilities
  "chalk": ^5.4.1
  "chokidar": ^3.6.0
  "dotenv": ^16.4.7
  "dotenv-cli": ^7.4.1

catalogs:

  database:
    "drizzle-orm": ^0.38.4
    "drizzle-kit": ^0.30.2
    "drizzle-zod": ^0.6.1
    "postgres": ^3.4.5
    "zod": ^3.23.10

  dev:
    # Build and Development Tools
    "@biomejs/biome": 1.9.4
    "@swc/cli": ^0.5.2
    "@swc/core": ^1.10.4
    "ts-node": ^10.9.2
    "tsx": ^4.19.2
    "turbo": ^2.3.3
    "typescript": ^5.7.2

    # Git Tools
    "@commitlint/cli": ^19.6.1
    "@commitlint/config-conventional": ^19.6.0
    "cz-conventional-changelog": ^3.3.0

  types:
    "@tsconfig/node23": ^23.0.0
    "@types/amqplib": ^0.10.6
    "@types/node": ^22.10.2
    "@types/pg": ^8.11.10
    "@types/jest": ^29.2.1
    "@types/chai": ^5.0.1
    "@types/mocha": ^10.0.10
    "@types/sinon": ^17.0.3

  test:
    # Testing Framework and Tools
    "tsconfig-paths": ^4.2.0
    "mocha": ^10.2.0
    "sinon": ^16.0.0
    "chai": ^4.3.7