packages:
  - apps/*
  - packages/*


catalog:
  "@biomejs/biome": 1.9.4
  "@commitlint/cli": ^19.6.1
  "@commitlint/config-conventional": ^19.6.0
  "@discordeno/bot": 21.0.0
  "@fastify/multipart": ^9.0.1
  "@influxdata/influxdb-client": ^1.35.0
  "@jest/globals": ^29.7.0
  "@swc/cli": ^0.5.2
  "@swc/core": ^1.10.4
  "@total-typescript/tsconfig": ^1.0.4
  "@types/amqplib": ^0.10.6
  "@types/node": ^22.10.2
  "@types/pg": ^8.11.10
  amqplib: ^0.10.5
  chalk: ^5.4.1
  chokidar: ^3.6.0
  cz-conventional-changelog: ^3.3.0
  fastify: ^5.2.0
  tsx: ^4.19.2
  turbo: ^2.3.3
  typescript: ^5.7.2
